In [2]:
import tensorflow as tf

In [3]:
tf.constant([[1, 2],[3, 4], [5, 6]], dtype=tf.float16)

Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



2022-06-10 16:21:31.030123: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-06-10 16:21:31.030461: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [4]:
tf.constant([

           [[0, 1, 2, 3, 4],

           [5, 6, 7, 8, 9]],

           [[10, 11, 12, 13, 14],

            [15, 16, 17, 18, 19]],

           [[20, 21, 22, 23, 24],

            [25, 26, 27, 28, 29]],])

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

In [5]:
t = tf.constant([

    [

         [2, 4, 4, 3] 

        ,[3, 2, 4, 5]

    ]

])

tf.shape(t)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 4], dtype=int32)>

In [6]:
t = tf.constant([

           [[0, 1, 2, 3, 4],

            [5, 6, 7, 8, 9]],

           [[10, 11, 12, 13, 14],

            [15, 16, 17, 18, 19]],

           [[20, 21, 22, 23, 24],

            [25, 26, 27, 28, 29]],])

tf.shape(t)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 2, 5], dtype=int32)>

In [7]:
t = tf.constant([2, 14, 10, 12, 15, 3, 2, 5, 15, 78])

In [8]:
t[:5]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2, 14, 10, 12, 15], dtype=int32)>

In [9]:
t[0::2]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2, 10, 15,  2, 15], dtype=int32)>

In [10]:
t = [ [3, 2, 1], [6, 5, 4], [9, 8, 7] ]  

In [11]:
t[1][0]

6

In [12]:
t = tf.constant([

           [[0, 1, 2, 3, 4],

            [5, 6, 7, 8, 9]],

           [[10, 11, 12, 13, 14],

            [15, 16, 17, 18, 19]],

           [[20, 21, 22, 23, 24],

            [25, 26, 27, 28, 29]],])

In [13]:
tf.shape(t)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 2, 5], dtype=int32)>

In [14]:
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>